---
agent: "Market1501Agent"

train:
  device: "cuda:0"
  n_epochs: 100
  logdir: "run/market1501"
  resume: false

dataset:
  size: [256, 128]
  root: "download"

dataloader:
  sampler:
    P: 16
    K: 4
  batch_size: 64

model:
  features: 128

loss:
  margin: 0.2

optimizer:
  lr: 0.001
  weight_decay: 0.0001
